# Generated by Django 3.0.6 on 2020-05-16 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreement', '0002_auto_20200514_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
