# Generated by Django 3.0.6 on 2020-05-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0003_auto_20200516_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('reg_number', models.CharField(max_length=50)),
                ('engine_number', models.CharField(max_length=100)),
                ('chassis_number', models.CharField(max_length=100)),
                ('odometer_reading', models.CharField(max_length=100)),
                ('regitered_car_owner', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_signature', models.ImageField(upload_to='signatures')),
                ('witness_one_name', models.CharField(max_length=50)),
                ('witness_one_signature', models.ImageField(upload_to='signatures/witness')),
                ('witness_one_id_number', models.IntegerField()),
                ('witness_one_phone_number', models.IntegerField()),
                ('witness_one_email', models.CharField(max_length=50)),
                ('witness_two_name', models.CharField(max_length=50)),
                ('witness_two_signature', models.ImageField(upload_to='signatures/witness')),
                ('witness_two_id_number', models.IntegerField()),
                ('witness_two_phone_number', models.IntegerField()),
                ('witness_two_email', models.CharField(max_length=50)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement.Buyer')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agreement.Item')),
            ],
        ),
    ]
