# Generated by Django 3.0.6 on 2020-05-28 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0005_auto_20200527_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='buyer_signature',
            field=models.ImageField(default='default.jpg', upload_to='signatures'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='witness_one_signature',
            field=models.ImageField(default='default.jpg', upload_to='signatures/witness'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='witness_two_signature',
            field=models.ImageField(default='default.jpg', upload_to='signatures/witness,'),
        ),
    ]
